include:
  - project: "innersource/sgts/ship-hats/ship-hats-templates"
    ref: "v1.0.9"
    file:
      - /templates/.gitlab-ci-docker-build.yml
      - /templates/.gitlab-ci-slsa-common.yml

.build-app:
  script:
    - echo "Implement extra building steps here."
  # artifacts:
  #   paths:
  #     - $OUTPUT_BUILD_ARTEFACT
  #   when: always
  #   reports:
  #     junit:
  #       - $WORKING_DIR/target/surefire-reports/TEST-*.xml

build-job: # do not change the name of this job without making updates to .gitlab-ci.yml
  extends: .build-app

build-image-job: # do not change the name of this job without making updates to .gitlab-ci.yml
  extends:
    - .build-docker-image # build docker images and export each image to tar file
    - .generate-gitlab-attestation
  needs: ["build-job"]
  variables:
    DOCKERFILE_PATH: $WORKING_DIR
    DOCKERFILE_NAME: "Dockerfile"
    OPTS: "" # Optional flags for Kaniko cmd
    OUTPUT_IMAGE_TAR: "$OUTPUT_IMAGE_ARTEFACT" # Override default output.tar
  before_script:
    - echo "Build Image"
  # artifacts:
  #   name: $ATTESTATION_ARTEFACT_NAME
  #   when: always
  #   paths:
  #     - $OUTPUT_IMAGE_ARTEFACT
