.deploy-docker:
  script:
    - echo "Implement deployment of docker image here."
    
deploy-prod-manual-job: # do not change the name of this job at all
  extends: .deploy-docker
  environment: # TODO: should be adaptable to different environment
    name: production
  when: manual
  allow_failure: false
